logging:
  level:
    root: WARN
server:
  port: 80
spring:
  application:
    name: server-end
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3506/hmk_manager
    username: root
    password: 111111
